import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import pluginNext from "@next/eslint-plugin-next";
import ts from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";
import pluginReact from "eslint-plugin-react";
import pluginReactHooks from "eslint-plugin-react-hooks";
import { plugin as shadcn } from "@shadcn/lint";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const eslintConfig = [
	// Configure global ignores (replaces .eslintignore)
	{
		ignores: [
			"node_modules/**",
			".cursor/**",
			".next/**",
			".vercel/**",
			".claude/**",
			"public/**",
			// tsconfig excludes (demo) examples; ESLint needs to match or it
			// can't find them in any TS project for type-aware linting.
			"src/app/(app)/(demo)/examples/**",
			"src/app/(demo)/**/*",
			// cli/ has its own tsconfig + toolchain and its deps aren't
			// installed by the root `bun install`; root tsconfig excludes it,
			// so type-aware linting can't resolve it here.
			"cli/**",
			"src/components/blocks/**",
			"src/components/ui/**",
			// Generated by `payload generate:types` — has tslint comments
			// and other style we don't enforce on generated code.
			"src/payload-types.ts",
			// Generated by fumadocs-mdx on every build; ships with @ts-nocheck
			// and isn't in the root tsconfig, so type-aware linting can't parse it.
			".source/**",
			// Standalone Holocron docs app — own tsconfig and toolchain, and its
			// dist/ is build output. See docs-site/README.md.
			"docs-site/**",
		],
	},

	// React flat config (avoids FlatCompat circular reference issue)
	{
		...pluginReact.configs.flat.recommended,
		settings: {
			react: { version: "detect" },
		},
		rules: {
			...(pluginReact.configs.flat.recommended?.rules ?? {}),
			// TS handles prop-types via types; the runtime prop-types lint rule is
			// noise here and produces 300+ false errors against typed components.
			"react/prop-types": "off",
		},
	},
	pluginReact.configs.flat["jsx-runtime"],

	// React Hooks
	{
		plugins: {
			"react-hooks": pluginReactHooks,
		},
		rules: pluginReactHooks.configs.recommended.rules,
	},

	// Next.js plugin (core-web-vitals includes recommended)
	{
		plugins: {
			"@next/next": pluginNext,
		},
		rules: {
			...pluginNext.configs.recommended.rules,
			...pluginNext.configs["core-web-vitals"].rules,
		},
	},

	// @shadcn/lint: Tailwind v4 design-system rules. Call sites only:
	// src/components/ui/** and src/components/blocks/** are excluded by the
	// global ignores above, so components can style their own internals.
	// Contracts and levels below are informed by a violation-count pass on
	// this codebase; see docs/development/index.mdx#design-system-lint.
	{
		files: ["**/*.{ts,tsx}"],
		languageOptions: {
			parser: tsParser,
			parserOptions: {
				ecmaVersion: "latest",
				sourceType: "module",
				ecmaFeatures: { jsx: true },
			},
		},
		plugins: { shadcn },
		rules: {
			"shadcn/no-restyle": [
				"warn",
				{
					allow: ["layout"],
					contracts: [
						{
							// Button (src/components/ui/button.tsx) owns its own
							// padding, height, radius, and type via `size`. Callers
							// get margin, width, and other layout/placement classes.
							// `{{sizes}}` only fills in on spacing findings (it's
							// literal otherwise per @shadcn/lint's docs), so height
							// (an explicit `deny`, category `layout`) gets its own
							// message instead of reusing the spacing one.
							pattern: "^Button$",
							allow: ["layout"],
							deny: ["h", "min-h", "max-h"],
							message: {
								spacing:
									'Button owns its padding via size. Use a Button size ({{sizes|none defined}}) from {{file}} instead of "{{className}}".',
								shape: 'Button\'s corner radius comes from its size in {{file}}. Use a size instead of "{{className}}".',
								typography:
									'Button\'s type comes from its size in {{file}}. Use a size instead of "{{className}}".',
								layout:
									'Button\'s height comes from its size in {{file}}. Use a size instead of "{{className}}", or margin/width here for placement.',
								default:
									'"{{className}}" is not allowed on <Button>. Use a variant ({{variants|none defined}}) or size from {{file}}, or margin/width here for placement.',
							},
						},
						{
							// CardTitle may resize its text but not change the
							// family or weight the design system sets.
							pattern: "^CardTitle$",
							allow: ["layout", "typography"],
							deny: ["font-*"],
							message: {
								typography:
									"CardTitle can resize its text (e.g. text-lg) but not its font family or weight. See {{file}}.",
								default:
									'"{{className}}" is not allowed on <CardTitle>. It can change layout and text size; other styling stays with the design system. See {{file}}.',
							},
						},
						{
							// CardContent may adjust spacing but not typography or
							// color; those stay with the design system.
							pattern: "^CardContent$",
							allow: ["layout", "spacing"],
							message: {
								default:
									'"{{className}}" is not allowed on <CardContent>. It can change layout and spacing (padding/gap); typography and color stay with the design system. See {{file}}.',
							},
						},
					],
				},
			],
			"shadcn/no-arbitrary-values": ["warn", { allow: ["layout"] }],
		},
	},

	// TypeScript files configuration
	{
		files: ["**/*.{ts,tsx}"],
		ignores: ["tests/**", "src/workers/**", "scripts/**"],
		languageOptions: {
			parser: tsParser,
			parserOptions: {
				project: ["./tsconfig.json"],
				tsconfigRootDir: __dirname,
				ecmaVersion: "latest",
				sourceType: "module",
				ecmaFeatures: {
					jsx: true,
				},
			},
		},
		plugins: {
			"@typescript-eslint": ts,
		},
		linterOptions: {
			reportUnusedDisableDirectives: true,
		},
		rules: {
			...(ts.configs["recommended-type-checked"]?.rules || {}),
			...(ts.configs["stylistic-type-checked"]?.rules || {}),
			"@typescript-eslint/no-unused-vars": [
				"warn",
				{
					argsIgnorePattern: "^_",
					varsIgnorePattern: "^_",
				},
			],
			"@typescript-eslint/consistent-type-imports": [
				"warn",
				{
					prefer: "type-imports",
					fixStyle: "inline-type-imports",
				},
			],
			"@typescript-eslint/ban-ts-comment": "warn",
			"@typescript-eslint/no-explicit-any": "warn",
			"@typescript-eslint/no-floating-promises": "warn",
			"@typescript-eslint/no-misused-promises": "warn",
			"@typescript-eslint/no-unsafe-argument": "warn",
			"@typescript-eslint/no-unsafe-assignment": "warn",
			"@typescript-eslint/no-unsafe-call": "warn",
			"@typescript-eslint/no-unsafe-member-access": "warn",
			"@typescript-eslint/no-unsafe-return": "warn",
		},
	},

	// Workers: use dedicated tsconfig for typed linting
	{
		files: ["src/workers/**/*.ts"],
		languageOptions: {
			parser: tsParser,
			parserOptions: {
				project: ["./tsconfig.workers.json"],
				tsconfigRootDir: __dirname,
				ecmaVersion: "latest",
				sourceType: "module",
				ecmaFeatures: {
					jsx: false,
				},
			},
		},
		plugins: {
			"@typescript-eslint": ts,
		},
	},

	// Build-tooling scripts: tsconfig excludes scripts/ for the same reason as
	// tests. Use non-project parser config.
	{
		files: ["scripts/**/*.{ts,tsx,mts,mjs}"],
		languageOptions: {
			parser: tsParser,
			parserOptions: {
				project: null,
				ecmaVersion: "latest",
				sourceType: "module",
			},
		},
		plugins: {
			"@typescript-eslint": ts,
		},
		rules: {
			"@typescript-eslint/prefer-nullish-coalescing": "off",
			"@typescript-eslint/no-floating-promises": "off",
			"@typescript-eslint/no-misused-promises": "off",
			"@typescript-eslint/no-unsafe-argument": "off",
			"@typescript-eslint/no-unsafe-assignment": "off",
			"@typescript-eslint/no-unsafe-call": "off",
			"@typescript-eslint/no-unsafe-member-access": "off",
			"@typescript-eslint/no-unsafe-return": "off",
			"@typescript-eslint/require-await": "off",
			"@typescript-eslint/no-base-to-string": "off",
			"@typescript-eslint/await-thenable": "off",
		},
	},

	// Tests: tsconfig excludes tests/ so type-aware linting can't parse them.
	// Use non-project parser config here to silence parser errors.
	{
		files: ["tests/**/*.{ts,tsx}"],
		languageOptions: {
			parser: tsParser,
			parserOptions: {
				project: null,
				ecmaVersion: "latest",
				sourceType: "module",
				ecmaFeatures: {
					jsx: true,
				},
			},
		},
		plugins: {
			"@typescript-eslint": ts,
		},
		rules: {
			// Type-aware rules require parserOptions.project; explicitly disable
			// them here to match the non-project parser.
			"@typescript-eslint/prefer-nullish-coalescing": "off",
			"@typescript-eslint/no-floating-promises": "off",
			"@typescript-eslint/no-misused-promises": "off",
			"@typescript-eslint/no-unsafe-argument": "off",
			"@typescript-eslint/no-unsafe-assignment": "off",
			"@typescript-eslint/no-unsafe-call": "off",
			"@typescript-eslint/no-unsafe-member-access": "off",
			"@typescript-eslint/no-unsafe-return": "off",
			"@typescript-eslint/require-await": "off",
			"@typescript-eslint/no-base-to-string": "off",
			"@typescript-eslint/await-thenable": "off",
		},
	},
];

export default eslintConfig;
